### ISSUE TITLE
Telemetry Integration

### ISSUE THREAD

**Issue by shaneutt** [Kong/gateway-operator#10]
### Problem Statement

We need anonymous reports to be able to indicate to us whether or not our Gateway Operator is in use, and a very high level of idea of _how_ it's being used.

### Acceptance Criteria

- [ ] telemetry functionality is added to the Gateway Operator. It is on by default, but can be flagged off if desired.
- [ ] telemetry reports on the number of `Gateway` resources created
- [ ] telemetry reports on the number of `DataPlanes` created, if NOT created by a `Gateway` (by checking owner ref)
- [ ] telemetry reports on the number of replicas requested for a `Gateway`/`DataPlane`
- [ ] telemetry reports on the number of `ControlPlanes` created, if NOT created by a `Gateway` (by checking owner ref)

**Comment by scseanchow** [comment]
Is this still blocked?

**Comment by shaneutt** [comment]
> Is this still blocked?

If we still plan to use a telemetry library rather than add the functionality in this repository, then yes this is still blocked.

**Comment by mflendrich** [comment]
Broken down into:
- https://github.com/Kong/team-k8s/issues/235
- https://github.com/Kong/gateway-operator/issues/122 dependent on the above
