### ISSUE TITLE
dataplane and controlplane deployments should use Red Hat UBI images when operator is running UBI image

### ISSUE THREAD

**Issue by jrsmroz** [Kong/gateway-operator#102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Currently, when user does not provide an image for a dataplane or a controlplane deployment, a default images is being used. The defaults are not based on Red Hat UBI image. 

One of the requirements for Red Hat certification is to base images on the Red Hat UBI base image. I believe it makes no sense to certify an operator image if it is going to pull non UBI images for deployments.

### Proposed Solution

- Operator uses the dedicated UBI images (if available) when the operator is running UBI itself.
- The decision can be made based on ENV variable.
- Because distroless and RedHat should be separate docker build targets, it's possible to set an ENV variable during build of a docker image.

### Acceptance Criteria

- [ ] When operator is running Red Hat Universal Base Image, the default images used for controlplane and dataplane deployments are UBI too, if available.
- [ ] When operator is not running distroless image, the images used for controlplane and dataplane deployments are disrtroless or equivalent.
- [ ] User can still overwrite the images for dataplane and controlplane deployments.

**Comment by rainest** [comment]
Historically we handled this through configuration, i.e. the default configuration we provided for the certified operator just used the UBI images everywhere we allowed configuring an image (and all images were configurable). Furthermore, they have you use a special operator-specific `RELATED_IMAGE_WHATEVER` set of variables in the _operator_ environment, which are then set to the UBI image in a CSV manifest: https://redhat-connect.gitbook.io/certified-operator-guide/troubleshooting-and-resources/offline-enabled-operators#golang-operators

AFAIK That specific format is necessary for OpenShift's offline tooling to pull images into a local cache and substitute the local version for the normal URL. Note that it needs these to be in a single `image:tag` string, whereas our configuration requires separate strings. We should consider simply changing the latter--they're not separate in the Kubernetes Container definition; aligning with that makes sense anyway.

**Comment by jrsmroz** [comment]
@rainest I think I'm lost here. To clarify, we should create a env variable `RELATED_IMAGE_KIC` and `RELATED_IMAGE_GATEWAY`, set them in CSV and let the operator read those env vals for defaults?

**Comment by rainest** [comment]
On further review, I think I'm incorrect. The naming looks maybe not actually necessary. The actual requirement is:

> Make sure your code is using environment variables for any images your operator uses

So we should actually be able to use any name we like.

For the Helm operator, we had those [in the operator environment and separately in watches.yaml](https://github.com/Kong/kong-operator/issues/76#issuecomment-1084913157), but in Helm's case you need to have something beyond environment variables: Helm only uses values.yaml to populate the template inputs, not the environment, so I suspect what watches.yaml is actually doing is providing items that the operator-sdk code should override using `--set` when it invokes `helm install`. The variables themselves aren't special, watches.yaml is, but it's only relevant to the standard Helm operator code.
