### ISSUE TITLE
Update default image tag of controlplane (KIC)

### ISSUE THREAD

**Issue by randmonkey** [Kong/gateway-operator#194]
Currently, gateway operator uses `2.3` as its default tag of control plane (KIC) image. Now KIC 2.4 and 2.5 has released and supported much more feature of gateway API, so it would better support gateway APIs if we update the default image tag to `2.5`. 

Since in KIC 2.6 and later, Gateway feature is by default enabled and a new feature `GatewayAlpha` is added, we need to also update the reconciling logic for controlplanes.

## Acceptance Criteria
- [ ] `DefaultControlPlaneTag` updated to `2.5` and gateway operator will deploy KIC 2.5 for controlplanes by default.

**Comment by randmonkey** [comment]
Seems that there was an issue https://github.com/Kong/gateway-operator/issues/29 for updating images, but it was gone.

**Comment by shaneutt** [comment]
Putting this into v0.1.0 as a stretch goal, seems like we should have plenty of time for it though since its tiny.
