### ISSUE TITLE
Log the version and commit hash on startup

### ISSUE THREAD

**Issue by mflendrich** [Kong/gateway-operator#201]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

I was writing up a bug report for https://github.com/Kong/gateway-operator/issues/200 (that runs `ghcr.io/kong/gateway-operator:main`) and realized that there's no obvious way (known to me at least) to identify the commit hash of the build I was using.

### Proposed Solution

On KGO startup, log the `internal/metadata` vars (`Release`, `Repo`, `Commit`).

### Additional information

KIC does this:

https://github.com/Kong/kubernetes-ingress-controller/blob/04fcf2a5ec00df5c9418c2bf6e612ac893db47c8/internal/manager/run.go#L41

### Acceptance Criteria

- [ ] As a user of KGO, I can read from logs the commit hash and the version number of KGO.

**Comment by mflendrich** [comment]
Shall we also log `struct Config`? https://github.com/Kong/kubernetes-ingress-controller/blob/73c6f7017416b6394f33a5caa884662dc7289d5f/internal/manager/config.go#L26?

**Comment by pmalek** [comment]
There is one way of printing the version: 

```
docker inspect --format "{{ .Config.Labels.version }}" ghcr.io/kong/gateway-operator:<TAG>
```

but it's not what we're interested in for the purposes of this issue.

Anyway: I added just that today in https://github.com/Kong/gateway-operator/pull/195. PTAL @mflendrich

**Comment by pmalek** [comment]
Reopening since #195 didn't add logging version at startup but upon adding the `-v` flag.
