### ISSUE TITLE
Gateway deployment broken on main due to redhat image defaults

### ISSUE THREAD

**Issue by shaneutt** [Kong/gateway-operator#266]
### Current Behavior

When I deployed the Gateway Operator this morning, and then deployed the normal `config/samples/gateway.yaml` example manifest, my `ControlPlane`'s `Pod` could not come up:

```
  Warning  Failed     7m31s (x4 over 9m6s)   kubelet            Failed to pull image "registry.connect.redhat.com/kong/kong-ingress-controller:2.5.0-redhat": rpc error: code = Unknown desc = failed to pull and unpack image "registry.connect.redhat.com/kong/kong-ingress-controller:2.5.0-redhat": failed to resolve reference "registry.connect.redhat.com/kong/kong-ingress-controller:2.5.0-redhat": failed to authorize: failed to fetch anonymous token: unexpected status: 401 Unauthorized
```

It's doing the same thing for the `DataPlane`:

```
  Warning  Failed     6s    kubelet            Failed to pull image "registry.connect.redhat.com/kong/kong:2.8.1": rpc error: code = Unknown desc = failed to pull and unpack image "registry.connect.redhat.com/kong/kong:2.8.1": failed to resolve reference "registry.connect.redhat.com/kong/kong:2.8.1": failed to authorize: failed to fetch anonymous token: unexpected status: 401 Unauthorized
```

There may be two problems here:

The image can not be retrieved.

This should not be the default.

### Expected Behavior

The `ControlPlane` and `DataPlane` should come up normally.

### Steps To Reproduce

```console
kubectl kustomize https://github.com/Kong/kubernetes-ingress-controller/config/crd | kubectl apply -f -
kubectl kustomize https://github.com/kubernetes-sigs/gateway-api/config/crd | kubectl apply -f -
kubectl kustomize config/default | kubectl apply -f -
kubectl -n kong-system wait --for=condition=Available=true --timeout=120s deployment/gateway-operator-controller-manager
kubectl apply -f config/samples/gateway.yaml
```

### Kong Gateway Operator version

33dfe6af016402fc8e77696d16cd22dc7addbd4e

### Kubernetes version

```shell
v1.24.0
```

### Notes

If I explicitly add the `kong/kubernetes-ingress-controller:2.5.0` image to the `GatewayConfiguration` this works around the broken default.

**Comment by jrsmroz** [comment]
By mistake the `RELATED_IMAGE_*` env vars were left in `config/manager/manager.yaml`. Those env vars should be defined only in overlay kustomize at `config/redhat-certified/manager_config_patch.yaml`
