### ISSUE TITLE
Sub-Resources are updated when owners are updated

### ISSUE THREAD

**Issue by shaneutt** [Kong/gateway-operator#27]
### Problem Statement

Currently if a `Gateway`, `ControlPlane` or `DataPlane` is updated this does not update the underlying owned resources.

### Prerequisites

- [x] #33 

### Acceptance Criteria

- [ ] updating a `Gateway` updates the underlying `ControlPlanes` and `DataPlanes` as needed
- [ ] updating a `GatewayConfiguration` updates the underlying `ControlPlanes` and `DataPlanes` as needed
- [ ] updating a `ControlPlane` updates the underlying `Deployments` as needed
- [ ] updating a `DataPlane` updates the underlying `Deployments` and `Services` as needed

### Additional Notes

- [ ] TODO comments which linked to this issue are removed once resolved

**Comment by mflendrich** [comment]
as @rainest mentioned: makes sense to do this after https://github.com/Kong/gateway-operator/pull/91 merges. Therefore making this issue as blocked.
