### ISSUE TITLE
Zero scale dormant `ControlPlanes`

### ISSUE THREAD

**Issue by shaneutt** [Kong/gateway-operator#32]
### Problem Statement

Technically it's possible to create a `ControlPlane` that isn't connected to any `DataPlane`. While a `ControlPlane` is in this state, we should scale it's `Deployment` down to `0` so that it's not wasting resources and making unnecessary noise.

### Acceptance Criteria

- [ ] A `ControlPlane` created OR updated with no `DataPlanes` results in a `Deployment` with no replicas
- [ ] Any update which adds a `DataPlane` reference then scales up the `Deployment`
- [ ] A `ControlPlane` in this "stagnant" state gets marked with a new, specific status indicating the holding state

**Comment by jrsmroz** [comment]
Is see few options here:
1. If data plane is not set, create a deployment scaled down to 0 replicas. That could handle the situation when data plane was removed from control plane.
2. If data plane is not set, refuse to proceed with provisioning, no deployment is created, just log the error and set the status.  Ignore the case when properly set data plane if removed from control plane.

The other thing is reporting.
1. Use `Type: ControlPlaneConditionTypeProvisioned` and a new dedicated `Reason`, i.e. `ControlPlaneConditionReasonNoDataPlane` 
2. Introduce a new `Status.Condition` to keep validation errors.

I actually would went with options 1 and 1, but I'm open for different options here.
