### ISSUE TITLE
Ensure that operator is certifiable in Red Hat Connect

### ISSUE THREAD

**Issue by shaneutt** [Kong/gateway-operator#49]
### Problem Statement

We want to have this operator present in the [OperatorHub](https://operatorhub.io/) and the [Red Hat Marketplance](https://marketplace.redhat.com) and be fully compatible with [OpenShift](https://www.redhat.com/technologies/cloud-computing/openshift).

In preparation for this, we need to:
- ensure that the gateway-operator image passes the RH Connect certification validations
- ensure that certification validations run on a regular basis on CI
- ensure that release images get pushed to the RH Connect image registry (and be available after scanning for subsequent publishing).

This issue captures those needs.

### Proposed Solution

- [ ] #59
- [ ] #57.
- [ ] #62

### Acceptance Criteria

- [ ] as a Kubernetes cluster operator I can deploy the Kong Gateway from OperatorHub
- [ ] the recent build of Gateway Operator (as well as KIC & Gateway) passes the certification workflow on GitHub.
- [ ] the recent build of Gateway Operator is staged for publishing on RH Marketplace.

**Comment by mflendrich** [comment]
Blocked upon completion of all issues mentioned in sub-items.

**Comment by shaneutt** [comment]
This issue is just the sum of its parts, it's a bag of holding so it doesn't need to remain open.
