### ISSUE TITLE
Leader election cannot be disabled

### ISSUE THREAD

**Issue by mlavacca** [Kong/gateway-operator#55]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In a testing/debugging environment, I would like to disable the leader election. This should be possible by not setting the `leader-elect` bool flag. The issue is that such a flag defaults to `true`, hence either setting or not setting the `leader-elect` bool var, the leader election is always set.

### Expected Behavior

One should be able to use or not the leader election. There are two possible solutions to this issue:
* leave the current flag, but default it to false (no leader election by default)
* change the `leader-elect` flag to `no-leader-election`, and default it to false (leader election by default).

**Comment by jrsmroz** [comment]
A few things:
1. Old flag actually could be used, `--leader-elect=false` is valid use case
2. `flag.Parse()` was missing. That is the main reason that it didn't have an effect.  https://github.com/Kong/gateway-operator/pull/72
