### ISSUE TITLE
Setting any controlplane env variable prevents default env vars from being created

### ISSUE THREAD

**Issue by jrsmroz** [Kong/gateway-operator#63]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently default environment variables in controlplane object created set only if none of custom env variables were provided during controlplane object creation. Providing any custom env variables prevents defaults to from being created.

[controllers/controlplane_controller.go#L57](https://github.com/Kong/gateway-operator/blob/main/controllers/controlplane_controller.go#L57):

```go
debug(log, "validating ControlPlane configuration", controlplane)
if len(controlplane.Spec.Env) == 0 && len(controlplane.Spec.EnvFrom) == 0 {
	debug(log, "no ENV config found for ControlPlane resource, setting defaults", controlplane)
	setControlPlaneDefaults(&controlplane.Spec.ControlPlaneDeploymentOptions, controlplane.Namespace, nil)
	if err := r.Client.Update(ctx, controlplane); err != nil {
		if errors.IsConflict(err) {
			debug(log, "conflict found when updating ControlPlane resource, retrying", controlplane)
			return ctrl.Result{Requeue: true, RequeueAfter: requeueWithoutBackoff}, nil
		}
		return ctrl.Result{}, err
	}
	return ctrl.Result{}, nil // no need to requeue, the update will trigger.
}
```

It's not clear to me if this is intended or not.

### Expected Behavior

To be clarified.

#### Manual
```markdown
1. Set any env variable in spec of controlplane object.
2. See that defaults like `POD_NAME`, `POD_NAMESPACE`, `CONTROLLER_PUBLISH_SERVICE`, `CONTROLLER_KONG_ADMIN_URL` are not created.
```

#### Tests

1. Create a controlplane with any env var set
```go
controlplane := &operatorv1alpha1.ControlPlane{
	ObjectMeta: metav1.ObjectMeta{
		Namespace: controlplaneName.Namespace,
		Name:      controlplaneName.Name,
	},
	Spec: operatorv1alpha1.ControlPlaneSpec{
		ControlPlaneDeploymentOptions: operatorv1alpha1.ControlPlaneDeploymentOptions{
			DeploymentOptions: operatorv1alpha1.DeploymentOptions{
				Env: []corev1.EnvVar{{
					Name:  testEnvVar,
					Value: testEnvVal,
				}},
			},
			DataPlane: &nameOfDataPlane,
		},
	},
}
```

or if using gateway:
```go
gatewayConfig := &operatorv1alpha1.GatewayConfiguration{
	ObjectMeta: metav1.ObjectMeta{
		Namespace: namespace.Name,
		Name:      uuid.NewString(),
	},
	Spec: operatorv1alpha1.GatewayConfigurationSpec{
		DataPlaneDeploymentOptions: &operatorv1alpha1.DataPlaneDeploymentOptions{
			DeploymentOptions: operatorv1alpha1.DeploymentOptions{
				Env: []corev1.EnvVar{{
					Name:  testEnvVar,
					Value: testEnvVal,
				}},
			},
		},
		ControlPlaneDeploymentOptions: &operatorv1alpha1.ControlPlaneDeploymentOptions{
			DeploymentOptions: operatorv1alpha1.DeploymentOptions{
				Env: []corev1.EnvVar{{
					Name:  testEnvVar,
					Value: testEnvVal,
				}},
			},
		},
	},
}
```
2. Controlplane controller will hit the line [controllers/controlplane_controller.go#L57](https://github.com/Kong/gateway-operator/blob/main/controllers/controlplane_controller.go#L57)
3. Env variables are not set in control plane.
4. When a new deployment for control plane is created [controllers/controlplane_controller_utils.go#L69](https://github.com/Kong/gateway-operator/blob/4bf93e0c3390bdb71dba13fe0510c4f3d1607a5b/controllers/controlplane_controller_utils.go#L69), the empty ENV is copied [controllers/controlplane_controller_utils.go#L104](https://github.com/Kong/gateway-operator/blob/4bf93e0c3390bdb71dba13fe0510c4f3d1607a5b/controllers/controlplane_controller_utils.go#L104)
5. Pods created from the deployment do not have the `CONTROLLER_KONG_ADMIN_URL` set. As a result KIC will assume its default admin API endpoint.
6. Connection to admin API fail with log message `Error: could not retrieve Kong admin root: making HTTP request: Get "http://localhost:8001/": dial tcp [::1]:8001: connect: connection refused`
7. Other implications? `POD_NAME`, `POD_NAMESPACE`, `CONTROLLER_PUBLISH_SERVICE` are not set in pods too.

### Kong Ingress Controller version

```shell
N/A
```

### Kubernetes version

```shell
N/A
```

**Comment by pmalek** [comment]
> Set any env variable in spec of controlplane object.

Do you mind providing examples (and ideally links to code) for those without the context?

**Comment by jrsmroz** [comment]
Updated the description with more details.

**Comment by shaneutt** [comment]
If I'm understanding this correctly I can verify this is a bug. Setting custom ENV vars should ONLY override those vars, any other unset var should still receive default values.

**Comment by jrsmroz** [comment]
Yes, that is how it behaves.
