### ISSUE TITLE
Improve Conditions handling for API objects

### ISSUE THREAD

**Issue by jrsmroz** [Kong/gateway-operator#66]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

There is  a limit of 8 entries per resource set in the API definition. Currently, when the condition needs to be updated, the code updates all the conditions that matches. In example:
```go
func (r *ControlPlaneReconciler) ensureControlPlaneIsMarkedProvisioned(
	ctx context.Context,
	controlplane *operatorv1alpha1.ControlPlane,
) error {
	updatedConditions := make([]metav1.Condition, 0)
	for _, condition := range controlplane.Status.Conditions {
		if condition.Type == string(ControlPlaneConditionTypeProvisioned) {
			condition.Status = metav1.ConditionTrue
			condition.Reason = ControlPlaneConditionReasonPodsReady
			condition.Message = "pods for all Deployments are ready"
			condition.ObservedGeneration = controlplane.Generation
			condition.LastTransitionTime = metav1.Now()
		}
		updatedConditions = append(updatedConditions, condition)
	}

	controlplane.Status.Conditions = updatedConditions
	return r.Status().Update(ctx, controlplane)
}
```

The Gateway implementation currently prunes the oldest conditions when a new one needs to be added. That's fine, as there is only single occurrence of given condition. But that's not really readable way to update single condition or safe, as if by any change we duplicate a conditions, we might reach the limit of 8.
Then we would need to decide which condition(s) to prune.

### Proposed Solution

- [ ] Ensure functions that set conditions cannot be misused by adding duplicate condition.
- [ ] Work out how to prune conditions, if limit of 8 is reached.

### Additional information

Add more robust logic for how this is handled and have a decision tree for which conditions need to be present and which don't or equivalent solution.

### Acceptance Criteria

- [ ] Ensure functions that set conditions cannot be misused by adding duplicate condition.
- [ ] Work out how to prune conditions, if limit of 8 is reached.

**Comment by jrsmroz** [comment]
@shaneutt Did I messed anything in the description?

**Comment by shaneutt** [comment]
Nope looks good.

**Comment by jrsmroz** [comment]
Pasting suggestions from Ruben Romero from the Slack chanal.

> I've been looking into the gateway-operator code and I would like to make some comments with my personal experience. It is mainly about the Status Condition management.
>
> Conditions as a snapshot: I'd suggest to treat the conditions as a snapshot of the current state, instead of a event log. This way you can read the current state of the Scheduled condition without having to sort by date. This helps with custom columns in the state, for example.
>
> Reason only when status=false. This is a common practice, if the condition is fine, no need to add a reason why it's fine.
Ready. It's very common to always have a Ready condition when all the other conditions are true. This simplifies objects observability.
>
> Suggested conditions for the Gateway. Scheduled, Ready, ControlPlaneReady, DataPlaneReady. The last ones are new
> What do you think? I don't mind working on a PR to make these changes if you find them useful.
>

> this doc helped me a lot in the past
> https://maelvls.dev/kubernetes-conditions/
