### ISSUE TITLE
Build and push new images for e2e tests 

### ISSUE THREAD

**Issue by randmonkey** [Kong/gateway-operator#77]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

e2e tests run in workflows for each PR uses the image in `config/manager/manager.yaml`. If anything in e2e test cases are changed, the old image does not contain the changes, and would cause an e2e fail. So we need to build and use a new image in each e2e run to test whether the source code can pass the e2e test cases in the same version. 

### Proposed Solution

Add workflows of build and push image in `test` workflow and replace image used for e2e test in each test.

### Acceptance Criteria

- [x] When run e2e tests for PRs, latest version of image is used in the e2e run.

**Comment by shaneutt** [comment]
We may be able to use what the KIC uses: the KTF image loader to make this work.

**Comment by randmonkey** [comment]
#39 already included this, so I think it could be closed.
